// Code generated by ogen, DO NOT EDIT.

package opayments

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreatePaymentRefund implements createPaymentRefund operation.
	//
	// Создать возврат.
	//
	// POST /payments/{paymentId}/refund
	CreatePaymentRefund(ctx context.Context, req *CreateRefundRequest, params CreatePaymentRefundParams) (CreatePaymentRefundRes, error)
	// CreateSbpPayment implements createSbpPayment operation.
	//
	// Создать платёж по СБП.
	//
	// POST /payments/sbp
	CreateSbpPayment(ctx context.Context, req *CreateSbpPaymentRequest) (CreateSbpPaymentRes, error)
	// CreateTpayPayment implements createTpayPayment operation.
	//
	// Создать платёж через T-Pay.
	//
	// POST /payments/tpay
	CreateTpayPayment(ctx context.Context, req *CreateTpayPaymentRequest) (CreateTpayPaymentRes, error)
	// GetBalance implements getBalance operation.
	//
	// Возвращает текущий баланс проекта.
	//
	// GET /balance
	GetBalance(ctx context.Context) (GetBalanceRes, error)
	// GetPayment implements getPayment operation.
	//
	// Получить платёж.
	//
	// GET /payments/{paymentId}
	GetPayment(ctx context.Context, params GetPaymentParams) (GetPaymentRes, error)
	// GetPaymentRefund implements getPaymentRefund operation.
	//
	// Получить возврат.
	//
	// GET /payments/{paymentId}/refund
	GetPaymentRefund(ctx context.Context, params GetPaymentRefundParams) (GetPaymentRefundRes, error)
	// ListPayments implements listPayments operation.
	//
	// Возвращает список платежей проекта.
	//
	// GET /payments
	ListPayments(ctx context.Context, params ListPaymentsParams) (ListPaymentsRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}

// WebhookHandler handles webhooks described by OpenAPI v3 specification.
type WebhookHandler interface {
	// DeliverPostpaymentWebhook implements deliverPostpaymentWebhook operation.
	//
	// Уведомление об изменении статуса платежа.
	//
	DeliverPostpaymentWebhook(ctx context.Context, req *PostpaymentWebhookNotification, params DeliverPostpaymentWebhookParams) (*DeliverPostpaymentWebhook2XX, error)
	// DeliverPrepaymentWebhook implements deliverPrepaymentWebhook operation.
	//
	// Предоплатная проверка.
	//
	DeliverPrepaymentWebhook(ctx context.Context, req *PrepaymentWebhookNotification, params DeliverPrepaymentWebhookParams) (*DeliverPrepaymentWebhook2XX, error)
	// DeliverRefundWebhook implements deliverRefundWebhook operation.
	//
	// Уведомление об изменении статуса возврата.
	//
	DeliverRefundWebhook(ctx context.Context, req *RefundWebhookNotification, params DeliverRefundWebhookParams) (*DeliverRefundWebhook2XX, error)
}

// WebhookServer implements http server based on OpenAPI v3 specification and
// calls WebhookHandler to handle requests.
type WebhookServer struct {
	h WebhookHandler
	baseServer
}

// NewWebhookServer creates new WebhookServer.
func NewWebhookServer(h WebhookHandler, opts ...ServerOption) (*WebhookServer, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &WebhookServer{
		h:          h,
		baseServer: s,
	}, nil
}
