// Code generated by ogen, DO NOT EDIT.

package opayments

import (
	"fmt"
	"net/http"
	"net/url"
	"time"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// CreatePaymentRefundParams is parameters of createPaymentRefund operation.
type CreatePaymentRefundParams struct {
	PaymentId uuid.UUID
}

func unpackCreatePaymentRefundParams(packed middleware.Parameters) (params CreatePaymentRefundParams) {
	{
		key := middleware.ParameterKey{
			Name: "paymentId",
			In:   "path",
		}
		params.PaymentId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeCreatePaymentRefundParams(args [1]string, argsEscaped bool, r *http.Request) (params CreatePaymentRefundParams, _ error) {
	// Decode path: paymentId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "paymentId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.PaymentId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "paymentId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetPaymentParams is parameters of getPayment operation.
type GetPaymentParams struct {
	PaymentId uuid.UUID
}

func unpackGetPaymentParams(packed middleware.Parameters) (params GetPaymentParams) {
	{
		key := middleware.ParameterKey{
			Name: "paymentId",
			In:   "path",
		}
		params.PaymentId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetPaymentParams(args [1]string, argsEscaped bool, r *http.Request) (params GetPaymentParams, _ error) {
	// Decode path: paymentId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "paymentId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.PaymentId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "paymentId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetPaymentRefundParams is parameters of getPaymentRefund operation.
type GetPaymentRefundParams struct {
	PaymentId uuid.UUID
}

func unpackGetPaymentRefundParams(packed middleware.Parameters) (params GetPaymentRefundParams) {
	{
		key := middleware.ParameterKey{
			Name: "paymentId",
			In:   "path",
		}
		params.PaymentId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetPaymentRefundParams(args [1]string, argsEscaped bool, r *http.Request) (params GetPaymentRefundParams, _ error) {
	// Decode path: paymentId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "paymentId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.PaymentId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "paymentId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ListPaymentsParams is parameters of listPayments operation.
type ListPaymentsParams struct {
	// Идентификатор заказа в системе мерчанта.
	OrderId       OptString             `json:",omitempty,omitzero"`
	Status        []PaymentStatusesItem `json:",omitempty"`
	PaymentMethod OptPaymentMethod      `json:",omitempty,omitzero"`
	// Не больше amountTo, если он передан.
	AmountFrom OptInt `json:",omitempty,omitzero"`
	// Не меньше amountFrom, если он передан.
	AmountTo OptInt `json:",omitempty,omitzero"`
	// Не позже createdTo, если он передан.
	CreatedFrom OptDateTime `json:",omitempty,omitzero"`
	// Не раньше createdFrom, если он передан.
	CreatedTo     OptDateTime      `json:",omitempty,omitzero"`
	Sort          OptSort          `json:",omitempty,omitzero"`
	SortDirection OptSortDirection `json:",omitempty,omitzero"`
	// Непрозрачный курсор из предыдущего ответа.
	// Используйте только с теми же фильтрами и сортировкой.
	Cursor OptString `json:",omitempty,omitzero"`
	// Количество записей в ответе.
	Limit OptInt `json:",omitempty,omitzero"`
}

func unpackListPaymentsParams(packed middleware.Parameters) (params ListPaymentsParams) {
	{
		key := middleware.ParameterKey{
			Name: "orderId",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.OrderId = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "status",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Status = v.([]PaymentStatusesItem)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "paymentMethod",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.PaymentMethod = v.(OptPaymentMethod)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "amountFrom",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.AmountFrom = v.(OptInt)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "amountTo",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.AmountTo = v.(OptInt)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "createdFrom",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.CreatedFrom = v.(OptDateTime)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "createdTo",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.CreatedTo = v.(OptDateTime)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "sort",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Sort = v.(OptSort)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "sortDirection",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.SortDirection = v.(OptSortDirection)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "cursor",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Cursor = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "limit",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Limit = v.(OptInt)
		}
	}
	return params
}

func decodeListPaymentsParams(args [0]string, argsEscaped bool, r *http.Request) (params ListPaymentsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: orderId.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "orderId",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotOrderIdVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotOrderIdVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.OrderId.SetTo(paramsDotOrderIdVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.OrderId.Get(); ok {
					if err := func() error {
						if err := (validate.String{
							MinLength:     0,
							MinLengthSet:  false,
							MaxLength:     128,
							MaxLengthSet:  true,
							Email:         false,
							Hostname:      false,
							Regex:         nil,
							MinNumeric:    0,
							MinNumericSet: false,
							MaxNumeric:    0,
							MaxNumericSet: false,
						}).Validate(string(value)); err != nil {
							return errors.Wrap(err, "string")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "orderId",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: status.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "status",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				params.Status = nil
				return d.DecodeArray(func(d uri.Decoder) error {
					var paramsDotStatusVal PaymentStatusesItem
					if err := func() error {
						val, err := d.DecodeValue()
						if err != nil {
							return err
						}

						c, err := conv.ToString(val)
						if err != nil {
							return err
						}

						paramsDotStatusVal = PaymentStatusesItem(c)
						return nil
					}(); err != nil {
						return err
					}
					params.Status = append(params.Status, paramsDotStatusVal)
					return nil
				})
			}); err != nil {
				return err
			}
			if err := func() error {
				var failures []validate.FieldError
				for i, elem := range params.Status {
					if err := func() error {
						if err := elem.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						failures = append(failures, validate.FieldError{
							Name:  fmt.Sprintf("[%d]", i),
							Error: err,
						})
					}
				}
				if len(failures) > 0 {
					return &validate.Error{Fields: failures}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "status",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: paymentMethod.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "paymentMethod",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotPaymentMethodVal PaymentMethod
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotPaymentMethodVal = PaymentMethod(c)
					return nil
				}(); err != nil {
					return err
				}
				params.PaymentMethod.SetTo(paramsDotPaymentMethodVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.PaymentMethod.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "paymentMethod",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: amountFrom.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "amountFrom",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotAmountFromVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotAmountFromVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.AmountFrom.SetTo(paramsDotAmountFromVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.AmountFrom.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           1,
							MaxSet:        false,
							Max:           0,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "amountFrom",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: amountTo.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "amountTo",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotAmountToVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotAmountToVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.AmountTo.SetTo(paramsDotAmountToVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.AmountTo.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           1,
							MaxSet:        false,
							Max:           0,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "amountTo",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: createdFrom.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "createdFrom",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCreatedFromVal time.Time
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToDateTime(val)
					if err != nil {
						return err
					}

					paramsDotCreatedFromVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.CreatedFrom.SetTo(paramsDotCreatedFromVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "createdFrom",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: createdTo.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "createdTo",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCreatedToVal time.Time
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToDateTime(val)
					if err != nil {
						return err
					}

					paramsDotCreatedToVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.CreatedTo.SetTo(paramsDotCreatedToVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "createdTo",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: sort.
	{
		val := Sort("createdAt")
		params.Sort.SetTo(val)
	}
	// Decode query: sort.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "sort",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotSortVal Sort
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotSortVal = Sort(c)
					return nil
				}(); err != nil {
					return err
				}
				params.Sort.SetTo(paramsDotSortVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Sort.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "sort",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: sortDirection.
	{
		val := SortDirection("desc")
		params.SortDirection.SetTo(val)
	}
	// Decode query: sortDirection.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "sortDirection",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotSortDirectionVal SortDirection
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotSortDirectionVal = SortDirection(c)
					return nil
				}(); err != nil {
					return err
				}
				params.SortDirection.SetTo(paramsDotSortDirectionVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.SortDirection.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "sortDirection",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: cursor.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "cursor",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCursorVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotCursorVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Cursor.SetTo(paramsDotCursorVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cursor",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: limit.
	{
		val := int(20)
		params.Limit.SetTo(val)
	}
	// Decode query: limit.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLimitVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotLimitVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Limit.SetTo(paramsDotLimitVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Limit.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           1,
							MaxSet:        true,
							Max:           100,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "limit",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// DeliverPostpaymentWebhookParams is parameters of deliverPostpaymentWebhook operation.
type DeliverPostpaymentWebhookParams struct {
	// Передаётся, если токен задан в настройках проекта.
	XWebhookToken OptString `json:",omitempty,omitzero"`
}

func unpackDeliverPostpaymentWebhookParams(packed middleware.Parameters) (params DeliverPostpaymentWebhookParams) {
	{
		key := middleware.ParameterKey{
			Name: "X-Webhook-Token",
			In:   "header",
		}
		if v, ok := packed[key]; ok {
			params.XWebhookToken = v.(OptString)
		}
	}
	return params
}

func decodeDeliverPostpaymentWebhookParams(args [0]string, argsEscaped bool, r *http.Request) (params DeliverPostpaymentWebhookParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: X-Webhook-Token.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-Webhook-Token",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotXWebhookTokenVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotXWebhookTokenVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.XWebhookToken.SetTo(paramsDotXWebhookTokenVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-Webhook-Token",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}

// DeliverPrepaymentWebhookParams is parameters of deliverPrepaymentWebhook operation.
type DeliverPrepaymentWebhookParams struct {
	// Передаётся, если токен задан в настройках проекта.
	XWebhookToken OptString `json:",omitempty,omitzero"`
}

func unpackDeliverPrepaymentWebhookParams(packed middleware.Parameters) (params DeliverPrepaymentWebhookParams) {
	{
		key := middleware.ParameterKey{
			Name: "X-Webhook-Token",
			In:   "header",
		}
		if v, ok := packed[key]; ok {
			params.XWebhookToken = v.(OptString)
		}
	}
	return params
}

func decodeDeliverPrepaymentWebhookParams(args [0]string, argsEscaped bool, r *http.Request) (params DeliverPrepaymentWebhookParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: X-Webhook-Token.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-Webhook-Token",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotXWebhookTokenVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotXWebhookTokenVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.XWebhookToken.SetTo(paramsDotXWebhookTokenVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-Webhook-Token",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}

// DeliverRefundWebhookParams is parameters of deliverRefundWebhook operation.
type DeliverRefundWebhookParams struct {
	// Передаётся, если токен задан в настройках проекта.
	XWebhookToken OptString `json:",omitempty,omitzero"`
}

func unpackDeliverRefundWebhookParams(packed middleware.Parameters) (params DeliverRefundWebhookParams) {
	{
		key := middleware.ParameterKey{
			Name: "X-Webhook-Token",
			In:   "header",
		}
		if v, ok := packed[key]; ok {
			params.XWebhookToken = v.(OptString)
		}
	}
	return params
}

func decodeDeliverRefundWebhookParams(args [0]string, argsEscaped bool, r *http.Request) (params DeliverRefundWebhookParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: X-Webhook-Token.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-Webhook-Token",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotXWebhookTokenVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotXWebhookTokenVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.XWebhookToken.SetTo(paramsDotXWebhookTokenVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-Webhook-Token",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}
