// Code generated by ogen, DO NOT EDIT.

package opayments

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreatePaymentRefund implements createPaymentRefund operation.
//
// Создать возврат.
//
// POST /payments/{paymentId}/refund
func (UnimplementedHandler) CreatePaymentRefund(ctx context.Context, req *CreateRefundRequest, params CreatePaymentRefundParams) (r CreatePaymentRefundRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSbpPayment implements createSbpPayment operation.
//
// Создать платёж по СБП.
//
// POST /payments/sbp
func (UnimplementedHandler) CreateSbpPayment(ctx context.Context, req *CreateSbpPaymentRequest) (r CreateSbpPaymentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTpayPayment implements createTpayPayment operation.
//
// Создать платёж через T-Pay.
//
// POST /payments/tpay
func (UnimplementedHandler) CreateTpayPayment(ctx context.Context, req *CreateTpayPaymentRequest) (r CreateTpayPaymentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetBalance implements getBalance operation.
//
// Возвращает текущий баланс проекта.
//
// GET /balance
func (UnimplementedHandler) GetBalance(ctx context.Context) (r GetBalanceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPayment implements getPayment operation.
//
// Получить платёж.
//
// GET /payments/{paymentId}
func (UnimplementedHandler) GetPayment(ctx context.Context, params GetPaymentParams) (r GetPaymentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPaymentRefund implements getPaymentRefund operation.
//
// Получить возврат.
//
// GET /payments/{paymentId}/refund
func (UnimplementedHandler) GetPaymentRefund(ctx context.Context, params GetPaymentRefundParams) (r GetPaymentRefundRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPayments implements listPayments operation.
//
// Возвращает список платежей проекта.
//
// GET /payments
func (UnimplementedHandler) ListPayments(ctx context.Context, params ListPaymentsParams) (r ListPaymentsRes, _ error) {
	return r, ht.ErrNotImplemented
}

var _ WebhookHandler = UnimplementedHandler{}

// DeliverPostpaymentWebhook implements deliverPostpaymentWebhook operation.
//
// Уведомление об изменении статуса платежа.
func (UnimplementedHandler) DeliverPostpaymentWebhook(ctx context.Context, req *PostpaymentWebhookNotification, params DeliverPostpaymentWebhookParams) (r *DeliverPostpaymentWebhook2XX, _ error) {
	return r, ht.ErrNotImplemented
}

// DeliverPrepaymentWebhook implements deliverPrepaymentWebhook operation.
//
// Предоплатная проверка.
func (UnimplementedHandler) DeliverPrepaymentWebhook(ctx context.Context, req *PrepaymentWebhookNotification, params DeliverPrepaymentWebhookParams) (r *DeliverPrepaymentWebhook2XX, _ error) {
	return r, ht.ErrNotImplemented
}

// DeliverRefundWebhook implements deliverRefundWebhook operation.
//
// Уведомление об изменении статуса возврата.
func (UnimplementedHandler) DeliverRefundWebhook(ctx context.Context, req *RefundWebhookNotification, params DeliverRefundWebhookParams) (r *DeliverRefundWebhook2XX, _ error) {
	return r, ht.ErrNotImplemented
}
