// Code generated by ogen, DO NOT EDIT.

package opayments

// OperationName is the ogen operation name
type OperationName = string

const (
	CreatePaymentRefundOperation       OperationName = "CreatePaymentRefund"
	CreateSbpPaymentOperation          OperationName = "CreateSbpPayment"
	CreateTpayPaymentOperation         OperationName = "CreateTpayPayment"
	GetBalanceOperation                OperationName = "GetBalance"
	GetPaymentOperation                OperationName = "GetPayment"
	GetPaymentRefundOperation          OperationName = "GetPaymentRefund"
	ListPaymentsOperation              OperationName = "ListPayments"
	DeliverPostpaymentWebhookOperation OperationName = "DeliverPostpaymentWebhook"
	DeliverPrepaymentWebhookOperation  OperationName = "DeliverPrepaymentWebhook"
	DeliverRefundWebhookOperation      OperationName = "DeliverRefundWebhook"
)
