// Code generated by ogen, DO NOT EDIT.
package opayments

type CreatePaymentRefundRes interface {
	createPaymentRefundRes()
}

type CreateSbpPaymentRes interface {
	createSbpPaymentRes()
}

type CreateTpayPaymentRes interface {
	createTpayPaymentRes()
}

type GetBalanceRes interface {
	getBalanceRes()
}

type GetPaymentRefundRes interface {
	getPaymentRefundRes()
}

type GetPaymentRes interface {
	getPaymentRes()
}

type ListPaymentsRes interface {
	listPaymentsRes()
}
