// Code generated by ogen, DO NOT EDIT.

package opayments

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleProjectIdentity handles ProjectIdentity security.
	HandleProjectIdentity(ctx context.Context, operationName OperationName, t ProjectIdentity) (context.Context, error)
	// HandleRequestSignature handles RequestSignature security.
	HandleRequestSignature(ctx context.Context, operationName OperationName, t RequestSignature) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

// operationRolesProjectIdentity is a private map storing roles per operation.
var operationRolesProjectIdentity = map[string][]string{
	CreatePaymentRefundOperation: []string{},
	CreateSbpPaymentOperation:    []string{},
	CreateTpayPaymentOperation:   []string{},
	GetBalanceOperation:          []string{},
	GetPaymentOperation:          []string{},
	GetPaymentRefundOperation:    []string{},
	ListPaymentsOperation:        []string{},
}

// GetRolesForProjectIdentity returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForProjectIdentity(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForProjectIdentity(operation string) []string {
	roles, ok := operationRolesProjectIdentity[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

// operationRolesRequestSignature is a private map storing roles per operation.
var operationRolesRequestSignature = map[string][]string{
	CreatePaymentRefundOperation: []string{},
	CreateSbpPaymentOperation:    []string{},
	CreateTpayPaymentOperation:   []string{},
	GetBalanceOperation:          []string{},
	GetPaymentOperation:          []string{},
	GetPaymentRefundOperation:    []string{},
	ListPaymentsOperation:        []string{},
}

// GetRolesForRequestSignature returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForRequestSignature(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForRequestSignature(operation string) []string {
	roles, ok := operationRolesRequestSignature[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Server) securityProjectIdentity(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t ProjectIdentity
	const parameterName = "X-Identity"
	value := req.Header.Get(parameterName)
	if value == "" {
		return ctx, false, nil
	}
	t.APIKey = value
	t.Roles = operationRolesProjectIdentity[operationName]
	rctx, err := s.sec.HandleProjectIdentity(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

func (s *Server) securityRequestSignature(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t RequestSignature
	const parameterName = "X-Signature"
	value := req.Header.Get(parameterName)
	if value == "" {
		return ctx, false, nil
	}
	t.APIKey = value
	t.Roles = operationRolesRequestSignature[operationName]
	rctx, err := s.sec.HandleRequestSignature(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// ProjectIdentity provides ProjectIdentity security value.
	ProjectIdentity(ctx context.Context, operationName OperationName) (ProjectIdentity, error)
	// RequestSignature provides RequestSignature security value.
	RequestSignature(ctx context.Context, operationName OperationName) (RequestSignature, error)
}

func (s *Client) securityProjectIdentity(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.ProjectIdentity(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"ProjectIdentity\"")
	}
	req.Header.Set("X-Identity", t.APIKey)
	return nil
}
func (s *Client) securityRequestSignature(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.RequestSignature(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"RequestSignature\"")
	}
	req.Header.Set("X-Signature", t.APIKey)
	return nil
}
